owner: chxseh # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Main Server
    url: https://chse.dev
  - name: Backup Server
    check: "tcp-ping"
    url: offsite-backup.chse.dev
    port: 1010

status-website:
  cname: uptime.chse.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
